version: "3.9"

services:
  sw_team_6_mysql:
    image: mysql:8.0
    container_name: sw_team_6_mysql
    ports:
      - "8506:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: wooriLearn
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sw_team_6_net

  backend:
    image: sw_team_6_backend:latest
    container_name: sw_team_6_backend
    ports:
      - "8580:8080"
    environment:
      SPRING_APPLICATION_NAME: bankedu-back
      SERVER_PORT: 8080

      # JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

      # CORS
      SPRING_WEB_CORS_ALLOWED_ORIGINS: http://192.168.0.79:8530
      SPRING_WEB_CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE,OPTIONS
      SPRING_WEB_CORS_ALLOW_CREDENTIALS: "true"

      # DB 환경 변수 (Jenkins → Compose → Spring)
      SPRING_DATASOURCE_URL: jdbc:mysql://sw_team_6_mysql:3306/wooriLearn
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

    depends_on:
      - sw_team_6_mysql
    networks:
      - sw_team_6_net

  frontend:
    image: sw_team_6_front:latest
    container_name: sw_team_6_front
    ports:
      - "8530:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://192.168.0.79:8580"
    depends_on:
      - backend
    networks:
      - sw_team_6_net

volumes:
  db_data:

networks:
  sw_team_6_net:
    external: true

