version: "3.9"

services:
  sw_team_6_mysql:
    image: mysql:8.0
    container_name: sw_team_6_mysql
    ports:
      - "8506:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wooriLearn
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sw_team_6_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sw_team_6_backend
    ports:
      - "8580:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sw_team_6_mysql:3306/wooriLearn?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - sw_team_6_mysql
    networks:
      - sw_team_6_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sw_team_6_frontend
    ports:
      - "8530:80"
    depends_on:
      - backend
    networks:
      - sw_team_6_net

volumes:
  db_data:

networks:
  sw_team_6_net:
    driver: bridge

