version: "3.9"

services:
  sw_team_6_mysql:
    image: mysql:8.0
    container_name: sw_team_6_mysql
    ports:
      - "8506:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: wooriLearn
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sw_team_6_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    image: sw_team_6_backend:latest
    container_name: sw_team_6_backend
    ports:
      - "8580:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sw_team_6_mysql:3306/wooriLearn
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      sw_team_6_mysql:
        condition: service_healthy
    networks:
      - sw_team_6_net

  frontend:
    image: sw_team_6_front:latest
    container_name: sw_team_6_front
    ports:
      - "8530:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://192.168.0.79:8580"
    depends_on:
      - backend
    networks:
      - sw_team_6_net

volumes:
  db_data:

networks:
  sw_team_6_net:

